name: app

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: [self-hosted, faax]
    steps:
      - uses: actions/checkout@v3
      - name: deploy faax
        run: echo Deploying faax
      - name: run docker
        env:
          TASKS_AI: ${{ vars.TASKS_AI }}
          TASKS_AI_MODEL: ${{ vars.TASKS_AI_MODEL }}
          ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: sudo -E docker compose --project-name=faax -f ./deployment/docker-compose.yml up faax --build --force-recreate --remove-orphans -d
      - name: prune images
        run: sudo docker image prune -a -f